#include "vk/format.hpp"

namespace uplift::vk {

VkFormat VkFormatOf(DXGI_FORMAT format) {
  switch (format) {
    case DXGI_FORMAT_B8G8R8A8_UNORM:      return VK_FORMAT_B8G8R8A8_UNORM;
    case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB: return VK_FORMAT_B8G8R8A8_SRGB;
    case DXGI_FORMAT_R8G8B8A8_UNORM:      return VK_FORMAT_R8G8B8A8_UNORM;
    case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB: return VK_FORMAT_R8G8B8A8_SRGB;
    case DXGI_FORMAT_R10G10B10A2_UNORM:   return VK_FORMAT_A2B10G10R10_UNORM_PACK32;
    case DXGI_FORMAT_R16G16B16A16_FLOAT:  return VK_FORMAT_R16G16B16A16_SFLOAT;
    case DXGI_FORMAT_R32G32B32A32_FLOAT:  return VK_FORMAT_R32G32B32A32_SFLOAT;
    case DXGI_FORMAT_R8_UNORM:            return VK_FORMAT_R8_UNORM;
    case DXGI_FORMAT_R16_FLOAT:           return VK_FORMAT_R16_SFLOAT;
    case DXGI_FORMAT_R16_UNORM:           return VK_FORMAT_R16_UNORM;
    case DXGI_FORMAT_R32_FLOAT:           return VK_FORMAT_R32_SFLOAT;
    case DXGI_FORMAT_R8G8_UNORM:          return VK_FORMAT_R8G8_UNORM;
    case DXGI_FORMAT_R16G16_FLOAT:        return VK_FORMAT_R16G16_SFLOAT;
    default:                              return VK_FORMAT_UNDEFINED;
  }
}

DXGI_FORMAT SharedFormatOf(DXGI_FORMAT format) {
  switch (format) {
    case DXGI_FORMAT_R8G8B8A8_TYPELESS:     return DXGI_FORMAT_R8G8B8A8_UNORM;
    case DXGI_FORMAT_B8G8R8A8_TYPELESS:     return DXGI_FORMAT_B8G8R8A8_UNORM;
    case DXGI_FORMAT_R10G10B10A2_TYPELESS:  return DXGI_FORMAT_R10G10B10A2_UNORM;
    case DXGI_FORMAT_R16G16B16A16_TYPELESS: return DXGI_FORMAT_R16G16B16A16_FLOAT;
    default:                                return format;
  }
}

}  // namespace uplift::vk
