# Plan 9 (design §2.2): writes UPLIFT_BUILD_ID = "<version>+<git short hash>[-dirty]" into ${UPLIFT_OUTPUT}, only when the
# text changed. Run at every build by the uplift_build_id target (cmake -P), not at configure time, so the two halves built
# from one tree always agree and halves from different trees are refused.
# A tree that is not a git checkout (a source archive such as GitHub's "Download ZIP") is "<version>+source"; without a
# usable git it is "<version>+unknown". The .git test comes first so that an archive unpacked inside some other repository
# does not take that repository's hash.
# Inputs: UPLIFT_SOURCE_DIR, UPLIFT_VERSION, UPLIFT_OUTPUT.

set(build_id "${UPLIFT_VERSION}+unknown")
if(NOT EXISTS "${UPLIFT_SOURCE_DIR}/.git")
  set(build_id "${UPLIFT_VERSION}+source")
else()
  find_program(git_program NAMES git)
  if(git_program)
    execute_process(
      COMMAND "${git_program}" -C "${UPLIFT_SOURCE_DIR}" rev-parse --short HEAD
      OUTPUT_VARIABLE git_hash OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE git_result)
    if(git_result EQUAL 0 AND NOT git_hash STREQUAL "")
      # Tracked files only: an untracked build folder or scratch file does not make a build "dirty". `git diff` compares content
      # where the index's stat data is stale (a touched or CRLF-converted file), which the plumbing `diff-index` reports as
      # modified; --no-optional-locks keeps the build from writing the index.
      execute_process(
        COMMAND "${git_program}" --no-optional-locks -C "${UPLIFT_SOURCE_DIR}" diff --quiet HEAD --
        ERROR_QUIET RESULT_VARIABLE git_dirty)
      if(git_dirty EQUAL 0)
        set(build_id "${UPLIFT_VERSION}+${git_hash}")
      else()
        set(build_id "${UPLIFT_VERSION}+${git_hash}-dirty")
      endif()
    endif()
  endif()
endif()

set(text "#pragma once\n\n// Generated by cmake/build_id.cmake at every build. Do not edit.\n#define UPLIFT_BUILD_ID \"${build_id}\"\n")
set(current "")
if(EXISTS "${UPLIFT_OUTPUT}")
  file(READ "${UPLIFT_OUTPUT}" current)
endif()
if(NOT current STREQUAL text)
  file(WRITE "${UPLIFT_OUTPUT}" "${text}")
endif()
